// Where wizardingcode-mem's binary lives and how to get it. Generated by scripts/plugins.ts.
import { createHash } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const VERSION = "0.3.0";
const REPO = "WizardingCode-io/wizardingcode-mem";
const MARKER = "@wizardingcode-mem-plugin";
const windows = process.platform === "win32";

export function binaryPath() {
  const home = process.env.WIZARDINGCODE_HOME || join(homedir(), ".wizardingcode");
  const data = process.env.WIZARDINGCODE_MEM_DATA_DIR || join(home, "mem");
  return join(data, "bin", windows ? "wizardingcode-mem.exe" : "wizardingcode-mem");
}

/** The plugin file `wizardingcode-mem install opencode` writes: when it is there, it speaks. */
export function directInstallPresent() {
  try {
    const config = process.env.XDG_CONFIG_HOME || join(homedir(), ".config");
    const file = join(config, "opencode", "plugins", "wizardingcode-mem.ts");
    return existsSync(file) && readFileSync(file, "utf8").includes(MARKER);
  } catch {
    return false;
  }
}

function installedVersion() {
  try {
    const out = Bun.spawnSync([binaryPath(), "--version"], { stdout: "pipe", stderr: "ignore" });
    return out.exitCode === 0 ? out.stdout.toString().trim() : null;
  } catch {
    return null;
  }
}

/** True when `have` is missing or older than `wanted`. A pre-release is older than its release; of two, the one that sorts first. */
export function older(have, wanted) {
  if (!have) return true;
  if (have === wanted) return false;
  const a = have.split(".").map((part) => Number.parseInt(part, 10) || 0);
  const b = wanted.split(".").map((part) => Number.parseInt(part, 10) || 0);
  for (let i = 0; i < 3; i++) {
    if ((a[i] ?? 0) < (b[i] ?? 0)) return true;
    if ((a[i] ?? 0) > (b[i] ?? 0)) return false;
  }
  if (have.includes("-") && !wanted.includes("-")) return true;
  return have.includes("-") && wanted.includes("-") && have < wanted;
}

/** Fetches the binary of this package's version when there is none, or an older one. */
export async function ensureBinary() {
  if (!older(installedVersion(), VERSION)) return;
  const platform = { darwin: "darwin", linux: "linux", win32: "windows" }[process.platform];
  const arch = { x64: "x64", arm64: "arm64" }[process.arch];
  if (!platform || !arch) return;
  const file = `wizardingcode-mem-${platform}-${arch}${windows ? ".exe" : ""}`;
  const base =
    process.env.WIZARDINGCODE_MEM_RELEASE_BASE || `https://github.com/${REPO}/releases/download/v${VERSION}`;
  const [binary, sums] = await Promise.all([fetch(`${base}/${file}`), fetch(`${base}/checksums.txt`)]);
  if (!binary.ok || !sums.ok) return;
  const bytes = Buffer.from(await binary.arrayBuffer());
  const expected = (await sums.text())
    .split("\n")
    .map((line) => line.trim().split(/\s+/))
    .find((parts) => parts[1] === file)?.[0];
  if (!expected || createHash("sha256").update(bytes).digest("hex") !== expected) return;
  const target = binaryPath();
  mkdirSync(join(target, ".."), { recursive: true });
  const temp = `${target}.${process.pid}`;
  writeFileSync(temp, bytes);
  chmodSync(temp, 0o755);
  renameSync(temp, target);
}
