#!/bin/sh
# wizardingcode-mem, as an agent's plugin runs it. One binary serves every agent, kept in
# ~/.wizardingcode/mem/bin; this script fetches it at the first session start (or when the
# plugin is newer than it) from the release of the plugin's version, checksum verified,
# and then hands over to it.
#
#   sh wizardingcode-mem.sh hook <agent> <session-start|prompt|turn-end|session-end>
#   sh wizardingcode-mem.sh mcp
#
# Fails open: whatever goes wrong in a hook, exit 0 with nothing on stdout.
# Generated by scripts/plugins.ts from scripts/templates/wizardingcode-mem.sh; do not edit a copy.

VERSION="0.4.3"
REPO="WizardingCode-io/wizardingcode-mem"

mode="${1:-}"
home="${WIZARDINGCODE_HOME:-$HOME/.wizardingcode}"
data="${WIZARDINGCODE_MEM_DATA_DIR:-$home/mem}"
bin="$data/bin/wizardingcode-mem"

# True when version $1 is missing or older than $2. A pre-release is older than its release,
# and of two pre-releases of one version the one that sorts first is the older.
older() {
  [ -z "$1" ] && return 0
  [ "$1" = "$2" ] && return 1
  awk -v a="$1" -v b="$2" 'BEGIN {
    split(a, x, "."); split(b, y, ".")
    for (i = 1; i <= 3; i++) { p = x[i] + 0; q = y[i] + 0; if (p < q) exit 0; if (p > q) exit 1 }
    if (a ~ /-/ && b !~ /-/) exit 0
    if (a ~ /-/ && b ~ /-/ && (a "") < (b "")) exit 0
    exit 1
  }'
}

fetch() {
  os="$(uname -s)"; arch="$(uname -m)"
  case "$os" in Darwin) os=darwin ;; Linux) os=linux ;; *) return 1 ;; esac
  case "$arch" in x86_64 | amd64) arch=x64 ;; arm64 | aarch64) arch=arm64 ;; *) return 1 ;; esac
  file="wizardingcode-mem-$os-$arch"
  base="${WIZARDINGCODE_MEM_RELEASE_BASE:-https://github.com/$REPO/releases/download/v$VERSION}"
  mkdir -p "$data/bin" || return 1
  tmp="$(mktemp "$data/bin/.wizardingcode-mem.XXXXXX")" || return 1
  curl -fsSL "$base/$file" -o "$tmp" || { rm -f "$tmp"; return 1; }
  expected="$(curl -fsSL "$base/checksums.txt" | awk -v f="$file" '$2 == f { print $1 }')"
  if command -v sha256sum > /dev/null 2>&1; then
    actual="$(sha256sum "$tmp" | awk '{ print $1 }')"
  else
    actual="$(shasum -a 256 "$tmp" | awk '{ print $1 }')"
  fi
  if [ -z "$expected" ] || [ "$actual" != "$expected" ]; then
    rm -f "$tmp"
    return 1
  fi
  chmod 755 "$tmp" && mv -f "$tmp" "$bin"
}

installed() {
  if [ -x "$bin" ]; then "$bin" --version 2> /dev/null || true; fi
}

case "$mode" in
  hook)
    if older "$(installed)" "$VERSION"; then
      # Only the session start fetches: a prompt or stop hook must not wait on a download.
      if [ "${3:-}" = "session-start" ]; then
        fetch > /dev/null 2>&1 || true
      fi
    fi
    [ -x "$bin" ] || exit 0
    exec "$bin" hook "${2:-}" "${3:-}" --via-plugin
    ;;
  mcp)
    # The host starts this alongside the first session-start hook, which may still be
    # fetching the binary: give it a moment before giving up.
    waited=0
    while [ ! -x "$bin" ] && [ "$waited" -lt 45 ]; do
      sleep 1
      waited=$((waited + 1))
    done
    [ -x "$bin" ] || exit 1
    exec "$bin" mcp
    ;;
  *)
    exit 0
    ;;
esac
