// Writes what each agent installs natively: the Claude Code plugin at the repository
// root, the Codex and Cursor plugins and the Gemini extension under plugins/, and the
// OpenCode plugin as an npm package. One source for names, versions and events; the
// files are committed because the agents read them from git, and a test keeps them in
// step with this script.
//
//   bun scripts/plugins.ts          write
//   bun scripts/plugins.ts --check  fail if any file differs
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import pkg from "../package.json" with { type: "json" };
import { CLAUDE_CODE } from "../src/install/claude-code.ts";
import { CODEX } from "../src/install/codex.ts";
import { CURSOR } from "../src/install/cursor.ts";
import { GEMINI } from "../src/install/gemini.ts";
import type { HostSpec } from "../src/install/hooks-file.ts";
import { PLUGIN_MARKER, pluginSource } from "../src/install/opencode-plugin.ts";

const ROOT = new URL("../", import.meta.url).pathname;
const NAME = "wizardingcode-mem";
const REPO = "WizardingCode-io/wizardingcode-mem";
const META = {
  description:
    "Persistent memory across sessions: what each session learns, the next one is told. One local binary, no daemon, no LLM in the loop; your plan is never spent on memory.",
  author: { name: "WizardingCode", url: "https://wizardingcode.io" },
  homepage: `https://github.com/${REPO}`,
  repository: `https://github.com/${REPO}`,
  license: "Apache-2.0",
  keywords: ["memory", "context", "wizardingcode", "sqlite", "local-first"],
};
// A session start may fetch the binary; the other events sit between the user and the model.
const START_TIMEOUT_SECONDS = 90;
const TIMEOUT_SECONDS = 5;

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
/** A placeholder the agent expands itself, spelled so that it is never JavaScript's. */
const ph = (name: string) => `$${"{"}${name}}`;
const seconds = (event: string) =>
  event === "session-start" ? START_TIMEOUT_SECONDS : TIMEOUT_SECONDS;

/** event → [{ hooks: [entry] }], the shape Claude Code, Codex and Gemini share. */
function grouped(spec: HostSpec, entry: (event: string) => Record<string, unknown>) {
  return {
    hooks: Object.fromEntries(
      spec.events.map(([hostEvent, event]) => [hostEvent, [{ hooks: [entry(event)] }]]),
    ),
  };
}

function script(version: string): string {
  return readFileSync(join(ROOT, "scripts/templates/wizardingcode-mem.sh"), "utf8").replace(
    "@VERSION@",
    version,
  );
}

/** binary.js of the OpenCode package: where the shared binary is, and how to fetch it. */
function opencodeBinary(version: string): string {
  return `// Where wizardingcode-mem's binary lives and how to get it. Generated by scripts/plugins.ts.
import { createHash } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const VERSION = ${JSON.stringify(version)};
const REPO = ${JSON.stringify(REPO)};
const MARKER = ${JSON.stringify(PLUGIN_MARKER)};
const windows = process.platform === "win32";

export function binaryPath() {
  const home = process.env.WIZARDINGCODE_HOME || join(homedir(), ".wizardingcode");
  const data = process.env.WIZARDINGCODE_MEM_DATA_DIR || join(home, "mem");
  return join(data, "bin", windows ? "wizardingcode-mem.exe" : "wizardingcode-mem");
}

/** The plugin file \`wizardingcode-mem install opencode\` writes: when it is there, it speaks. */
export function directInstallPresent() {
  try {
    const config = process.env.XDG_CONFIG_HOME || join(homedir(), ".config");
    const file = join(config, "opencode", "plugins", "wizardingcode-mem.ts");
    return existsSync(file) && readFileSync(file, "utf8").includes(MARKER);
  } catch {
    return false;
  }
}

function installedVersion() {
  try {
    const out = Bun.spawnSync([binaryPath(), "--version"], { stdout: "pipe", stderr: "ignore" });
    return out.exitCode === 0 ? out.stdout.toString().trim() : null;
  } catch {
    return null;
  }
}

/** True when \`have\` is missing or older than \`wanted\`. A pre-release is older than its release; of two, the one that sorts first. */
export function older(have, wanted) {
  if (!have) return true;
  if (have === wanted) return false;
  const a = have.split(".").map((part) => Number.parseInt(part, 10) || 0);
  const b = wanted.split(".").map((part) => Number.parseInt(part, 10) || 0);
  for (let i = 0; i < 3; i++) {
    if ((a[i] ?? 0) < (b[i] ?? 0)) return true;
    if ((a[i] ?? 0) > (b[i] ?? 0)) return false;
  }
  if (have.includes("-") && !wanted.includes("-")) return true;
  return have.includes("-") && wanted.includes("-") && have < wanted;
}

/** Fetches the binary of this package's version when there is none, or an older one. */
export async function ensureBinary() {
  if (!older(installedVersion(), VERSION)) return;
  const platform = { darwin: "darwin", linux: "linux", win32: "windows" }[process.platform];
  const arch = { x64: "x64", arm64: "arm64" }[process.arch];
  if (!platform || !arch) return;
  const file = \`wizardingcode-mem-\${platform}-\${arch}\${windows ? ".exe" : ""}\`;
  const base =
    process.env.WIZARDINGCODE_MEM_RELEASE_BASE || \`https://github.com/\${REPO}/releases/download/v\${VERSION}\`;
  const [binary, sums] = await Promise.all([fetch(\`\${base}/\${file}\`), fetch(\`\${base}/checksums.txt\`)]);
  if (!binary.ok || !sums.ok) return;
  const bytes = Buffer.from(await binary.arrayBuffer());
  const expected = (await sums.text())
    .split("\\n")
    .map((line) => line.trim().split(/\\s+/))
    .find((parts) => parts[1] === file)?.[0];
  if (!expected || createHash("sha256").update(bytes).digest("hex") !== expected) return;
  const target = binaryPath();
  mkdirSync(join(target, ".."), { recursive: true });
  const temp = \`\${target}.\${process.pid}\`;
  writeFileSync(temp, bytes);
  chmodSync(temp, 0o755);
  renameSync(temp, target);
}
`;
}

/** Every generated file, by its path from the repository root. */
export function generated(version: string = pkg.version): Record<string, string> {
  const sh = script(version);
  const shell = (root: string, agent: string, event: string) =>
    `sh "${root}/wizardingcode-mem.sh" hook ${agent} ${event}`;

  return {
    // Claude Code: the repository root is the plugin. Exec form, no shell in between.
    ".claude-plugin/plugin.json": json({
      name: NAME,
      displayName: NAME,
      version,
      ...META,
      mcpServers: {
        [NAME]: {
          command: "sh",
          args: [`${ph("CLAUDE_PLUGIN_ROOT")}/plugin/wizardingcode-mem.sh`, "mcp"],
        },
      },
    }),
    "hooks/hooks.json": json(
      grouped(CLAUDE_CODE, (event) => ({
        type: "command",
        command: "sh",
        args: [
          `${ph("CLAUDE_PLUGIN_ROOT")}/plugin/wizardingcode-mem.sh`,
          "hook",
          "claude-code",
          event,
        ],
        timeout: seconds(event),
      })),
    ),
    "plugin/wizardingcode-mem.sh": sh,

    // Codex: a hook's command is one shell string; the plugin's directory is ${PLUGIN_ROOT}.
    "plugins/codex/.codex-plugin/plugin.json": json({
      name: NAME,
      version,
      ...META,
      mcpServers: "./.mcp.json",
    }),
    "plugins/codex/hooks/hooks.json": json(
      grouped(CODEX, (event) => ({
        type: "command",
        command: shell(ph("PLUGIN_ROOT"), "codex", event),
        timeout: seconds(event),
      })),
    ),
    "plugins/codex/.mcp.json": json({
      mcpServers: {
        [NAME]: { command: "sh", args: [`${ph("PLUGIN_ROOT")}/wizardingcode-mem.sh`, "mcp"] },
      },
    }),
    "plugins/codex/wizardingcode-mem.sh": sh,

    // Gemini CLI: the release archive carries the binary in bin/, so nothing is fetched.
    "plugins/gemini/gemini-extension.json": json({
      name: NAME,
      version,
      description: META.description,
      mcpServers: {
        [NAME]: {
          command: `${ph("extensionPath")}${ph("/")}bin${ph("/")}wizardingcode-mem`,
          args: ["mcp"],
        },
      },
    }),
    "plugins/gemini/hooks/hooks.json": json(
      grouped(GEMINI, (event) => ({
        name: NAME,
        type: "command",
        command: `"${ph("extensionPath")}/bin/wizardingcode-mem" hook gemini ${event} --via-plugin`,
        timeout: TIMEOUT_SECONDS * 1000,
      })),
    ),

    // Cursor: a flat list of entries per event.
    "plugins/cursor/.cursor-plugin/plugin.json": json({ name: NAME, version, ...META }),
    "plugins/cursor/hooks/hooks.json": json({
      version: 1,
      hooks: Object.fromEntries(
        CURSOR.events.map(([hostEvent, event]) => [
          hostEvent,
          [{ command: shell(ph("CURSOR_PLUGIN_ROOT"), "cursor", event), timeout: seconds(event) }],
        ]),
      ),
    }),
    "plugins/cursor/mcp.json": json({
      mcpServers: {
        [NAME]: {
          command: "sh",
          args: [`${ph("CURSOR_PLUGIN_ROOT")}/wizardingcode-mem.sh`, "mcp"],
        },
      },
    }),
    "plugins/cursor/wizardingcode-mem.sh": sh,

    // OpenCode: an npm package of its own, because its tools need OpenCode's plugin API.
    "plugins/opencode/package.json": json({
      name: "wizardingcode-mem-opencode",
      version,
      description: `${NAME} for OpenCode. ${META.description}`,
      type: "module",
      main: "./index.js",
      exports: { ".": "./index.js" },
      files: ["index.js", "binary.js", "README.md"],
      dependencies: { "@opencode-ai/plugin": ">=1.0.0" },
      license: META.license,
      author: META.author.name,
      homepage: META.homepage,
      repository: {
        type: "git",
        url: `git+https://github.com/${REPO}.git`,
        directory: "plugins/opencode",
      },
      keywords: ["opencode", "opencode-plugin", ...META.keywords],
    }),
    "plugins/opencode/index.js": pluginSource("npm"),
    "plugins/opencode/binary.js": opencodeBinary(version),
    "plugins/opencode/README.md": `# wizardingcode-mem for OpenCode

\`\`\`
opencode plugin wizardingcode-mem-opencode --global
\`\`\`

Persistent memory for OpenCode sessions, shared with Claude Code, Codex, Cursor and Gemini CLI. The plugin fetches the [wizardingcode-mem](https://github.com/${REPO}) binary of its own version on first use (checksum verified) and keeps it in \`~/.wizardingcode/mem/bin\`. Memories live in \`~/.wizardingcode/mem\`.
`,
  };
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const stale: string[] = [];
  for (const [path, content] of Object.entries(generated())) {
    const file = join(ROOT, path);
    let current: string | null = null;
    try {
      current = readFileSync(file, "utf8");
    } catch {
      current = null;
    }
    if (current === content) continue;
    if (check) {
      stale.push(path);
      continue;
    }
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content, path.endsWith(".sh") ? { mode: 0o755 } : {});
    console.log(`wrote ${path}`);
  }
  if (stale.length > 0) {
    console.error(`out of date (run \`bun scripts/plugins.ts\`):\n  ${stale.join("\n  ")}`);
    process.exit(1);
  }
}
